### ISSUE TITLE
Original URL exposed

### ISSUE THREAD

**Issue by ubaydkhan** [tomatohater/django-unfriendly#18]
Hey. I was wondering what could be causing my original URLs to still be live. Does django-unfriendly not do anything to stop for example, "/post/1" be entered. Currently the obfuscation works but it's just that having the original URL is very annoying and particularly destroys the purpose in my case. Thanks.

**Comment by tomatohater** [comment]
This is a great question... Thanks for asking.
At this time, the app does not interfere with the original url. It's sole purpose is to create obfuscated urls that function exactly as the original. If the original urls are never exposed, there will be no need to block them.
However... I have definitely considered this use case. Django-unfriendly really wouldn't know even which URLs to disable... So I was considering creating a different Django app which can disable URLs, and can be used in tandem with Django-unfriendly to achieve the effect you desire.
The reason I haven't done so already is that I didn't think there was interest. If I were to create such an app... Would you use it? And what might you name it? :)







On Fri, Aug 12, 2016 at 7:46 PM -0700, "Ubayd Khan" <notifications@github.com> wrote:












Hey. I was wondering what could be causing my original URLs to still be live. Does django-unfriendly not do anything to stop for example, "/post/1" be entered. Currently the obfuscation works but it's just that having the original URL is very annoying and particularly destroys the purpose in my case. Thanks.

**Comment by ubaydkhan** [comment]
@tomatohater Sorry for the late reply. Yes I would definitely use it.  And I don't know what I would name it...maybe django-struggle. I'm not the best at naming things. 😂

**Comment by tomatohater** [comment]
@ubaydkhan I haven't published to Pypi yet, but it works:
https://github.com/tomatohater/django-shyurl

I just need to add automated tests then I'll publish it.

Let me know if you have any comments or suggestions.

**Comment by tomatohater** [comment]
Hi @ubaydkhan 

I'm just checking into see if this new library solves your issue. All feedback is welcomed.
